version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"
    environment:
      TZ: "America/New_York"  

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - "database"
      - "redis"
    environment:
      TZ: "America/New_York"  

  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      TZ: "America/New_York"  
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      TZ: "America/New_York" 

volumes:
  postgres_data:
  redis_data:
